### ISSUE TITLE
RS485 / Modbus communication using a Raspberry Pi 3B and a Seeed Shield 

### ISSUE THREAD

**Issue by lg007** [xiegeo/modbusone#1]
First of all, let me congratulate for this fabulous package!

I had to implement an RS-485 (Modbus) interface on an RPI 3B using a Seeed RS-485 Shield. I have done the whole process (together with other processes) with RXJAVA using Pi4J (which uses the Wiringpi library) and it works fine. But I have to port the whole system to C or GO because of performance (speed) reasons. And I definitely prefer doing it in GO and if possible, by using your package with some little modifications. The modifications are needed because the Seeed Shield uses a GPIO pin to set the data flow direction of the RS485 communication.  

To use the Seeed Shield, the following has to be done:
- Turn an output pin high (BCM 18) to set the communication direction of the shield to transmission,
- Send a command to the Modbus device,
- Turn the output pin (BCM 18) to low to set the shield to reception,
- Read in the answer of the Modbus device.

I will gladly write (and publish) the modifications, however it would be much faster if you could send me some advice. I would appreciate if you could me pinpoint the points in the code where the transmission turns into reception and viceversa. Toggling a GPIO pin on the raspberry can be easily done with existing open source packages, so this part of the project is relatively easy. 

Of course if my request is too much, just forget it, I will inspect the code myself.

Regards,

**Comment by xiegeo** [comment]
Great to hear from you, I am currently travelling so please excuse my untimeliness.

I would suggest you to write an `io.ReadWriteCloser` that includes the flow direction code. There shouldn't be any need to modify this library, but if it helps, you can send a pull request.

**Comment by lg007** [comment]
Thanks, I will do as you suggest.
