### ISSUE TITLE
Add version tag to current master

### ISSUE THREAD

**Issue by orlopau** [xiegeo/modbusone#2]
Hi,

first and foremost thanks for the library, its amazing.

Could you add a version tag to the current master? 
Else when using `go get github.com/xiegeo/modbusone` without explicitly specifying `@master`, an outdated dependency is pulled.

Thank you very much :smiley:

**Comment by xiegeo** [comment]
Nice catch! TCP support was under development, so I wasn't ready to tag a release, then the project got on the back burner. I will tag a new release soon once I handle some of the bit rot.

**Comment by xiegeo** [comment]
V1.0.0 is now released.
